### ISSUE TITLE
Feature Request: Allow to make keystroke louder

### ISSUE THREAD

**Issue by j-martin** [x0054/MKS#1]
I usually use NoisyTyper so I can hear my keystrokes while listening to music. MKS's volume seems much lower than NoisyTyper. It would be nice to be able to make the keystrokes even louder.

Workaround: Lowering the volume of the background music.

PS: Thanks for writing an alternative to NoisyTyper, I was considering writing my own, now there is MKS. :)

**Comment by x0054** [comment]
The sound is already at 100%, but I just realized that I can amplify the keystroke wave file, so it's just a matter of replacing the wav files. I'll update this shortly and incorporate another feature someone asked for.

**Comment by j-martin** [comment]
Yes, I was thinking about increasing the gain on the wave files. `Tappy Profile #2` is the best btw. :)

**Comment by x0054** [comment]
Yep, new release upped the gain on both profile 1 and 2 and added the random pitch and volume option (optional, can be set in the menu).

**Comment by j-martin** [comment]
Thanks! I'll give it a try once #4 is fixed.
