### ISSUE TITLE
Bug: no MKS sounds in password fields

### ISSUE THREAD

**Issue by erikr** [x0054/MKS#3]
OS: 10.14.2
Browser: Safari 12.0.2 (reproduces in Chrome 71.0.3578.98)
Issue: no MKS sounds in password fields (sounds work just fine in username fields)

**Comment by x0054** [comment]
This is not a bug actually, it's a security feature of MacOS. MacOS prevents any app from being able to capture the keys when you are typing in the password field, it's to prevent keyloggers from capturing your passwords.
