### ISSUE TITLE
MKS 1.5 dmg is corrupted

### ISSUE THREAD

**Issue by j-martin** [x0054/MKS#4]
Hi, 

I am getting this error with build 1.5. Also, I noticed that the DMG doubled in size to 4.3MB. I have not checked why the size changed.

![image](https://user-images.githubusercontent.com/4259753/51352281-0258c500-1a62-11e9-993e-41faac0541a2.png)

**Comment by x0054** [comment]
Hmm, I am not sure why it didn't work. I recompiled and just updated the DMG. Give it a try. As for the size difference, the coded didn't change much but the previous version of the app was compiled using older xcode and this one was compiled Xcode 10 and for some reason it included a bunch more frameworks. I was going to figure out why, but I just don't have time today. You can always just compile it in Xcode from source, it doesn't need any additional libraries.

**Comment by j-martin** [comment]
I am still getting the issue. I am on Mojave (10.14.2). The timestamp on the extracted app is 2019-01-17T22:00Z. I might still be getting the original release pushed earlier today.

The error below is if you start the application after uncompressing it. The one above was from running MKS.app directly from the DMG.

![image](https://user-images.githubusercontent.com/4259753/51356863-15bf5c80-1a71-11e9-8ce3-d7bfed548582.png)

I don't have Xcode installed on my machine so I can't compile it without losing ~10GB of disk space.

**Comment by j-martin** [comment]
Actually, it seems the issue was macOS being confused with which DMG to run. Things are working fine now.

Sorry for the confusion.
